// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanD.Api.Data;

#nullable disable

namespace PlanD.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001211959_BrokerManagement")]
    partial class BrokerManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_broker_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_broker_claims_user_id");

                    b.ToTable("broker_claims", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_broker_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_broker_logins_user_id");

                    b.ToTable("broker_logins", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_broker_tokens");

                    b.ToTable("broker_tokens", "app");
                });

            modelBuilder.Entity("PlanD.Api.Data.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_agencies");

                    b.ToTable("agencies", "app");
                });

            modelBuilder.Entity("PlanD.Api.Data.BrokerCarrier", b =>
                {
                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_id");

                    b.Property<string>("ParentOrganization")
                        .HasColumnType("text")
                        .HasColumnName("parent_organization");

                    b.HasKey("BrokerId", "ParentOrganization")
                        .HasName("pk_broker_carriers");

                    b.ToTable("broker_carriers", "app");
                });

            modelBuilder.Entity("PlanD.Api.Data.BrokerInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedById")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_broker_invites");

                    b.HasIndex("InvitedById")
                        .HasDatabaseName("ix_broker_invites_invited_by_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_broker_invites_token_hash");

                    b.HasIndex("AgencyId", "Email")
                        .HasDatabaseName("ix_broker_invites_agency_id_email");

                    b.ToTable("broker_invites", "app");
                });

            modelBuilder.Entity("PlanD.Api.Data.BrokerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTimeOffset?>("LastSignInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sign_in_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("PublicSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_slug");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_brokers");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_brokers_agency_id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PublicSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_brokers_public_slug");

                    b.ToTable("brokers", "app");
                });

            modelBuilder.Entity("PlanD.Api.Data.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<int?>("BirthMonth")
                        .HasColumnType("integer")
                        .HasColumnName("birth_month");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_id");

                    b.Property<string>("CountyCode")
                        .HasColumnType("text")
                        .HasColumnName("county_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentPlan")
                        .HasColumnType("text")
                        .HasColumnName("current_plan");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExtraHelp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extra_help");

                    b.Property<int>("ExtraHelpLevel")
                        .HasColumnType("integer")
                        .HasColumnName("extra_help_level");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MedicareStatus")
                        .HasColumnType("text")
                        .HasColumnName("medicare_status");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("SeenByBrokerAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seen_by_broker_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UsesMailOrder")
                        .HasColumnType("boolean")
                        .HasColumnName("uses_mail_order");

                    b.Property<string>("Zip")
                        .HasColumnType("text")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("BrokerId")
                        .HasDatabaseName("ix_clients_broker_id");

                    b.HasIndex("AgencyId", "BrokerId", "Status")
                        .HasDatabaseName("ix_clients_agency_id_broker_id_status");

                    b.ToTable("clients", "app");
                });

            modelBuilder.Entity("PlanD.Api.Data.ClientDrug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<int>("DaysSupply")
                        .HasColumnType("integer")
                        .HasColumnName("days_supply");

                    b.Property<decimal>("DosesPerDay")
                        .HasColumnType("numeric")
                        .HasColumnName("doses_per_day");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Rxcui")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rxcui");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<decimal>("UnitsPerDose")
                        .HasColumnType("numeric")
                        .HasColumnName("units_per_dose");

                    b.HasKey("Id")
                        .HasName("pk_client_drugs");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_drugs_client_id");

                    b.ToTable("client_drugs", "app");
                });

            modelBuilder.Entity("PlanD.Api.Data.ClientNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_client_notes");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_notes_client_id");

                    b.ToTable("client_notes", "app");
                });

            modelBuilder.Entity("PlanD.Api.Data.ClientPharmacy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Npi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("npi");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Zip")
                        .HasColumnType("text")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_client_pharmacies");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_pharmacies_client_id");

                    b.ToTable("client_pharmacies", "app");
                });

            modelBuilder.Entity("PlanD.Api.Data.Consent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("TextVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_version");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_consents");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_consents_client_id");

                    b.ToTable("consents", "app");
                });

            modelBuilder.Entity("PlanD.Api.Data.PatientLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_patient_links");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_patient_links_client_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_patient_links_token_hash");

                    b.ToTable("patient_links", "app");
                });

            modelBuilder.Entity("PlanD.Api.Data.QuoteSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("LandscapeReleaseId")
                        .HasColumnType("integer")
                        .HasColumnName("landscape_release_id");

                    b.Property<int>("PlanYear")
                        .HasColumnType("integer")
                        .HasColumnName("plan_year");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_json");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<int>("SpufReleaseId")
                        .HasColumnType("integer")
                        .HasColumnName("spuf_release_id");

                    b.HasKey("Id")
                        .HasName("pk_quote_snapshots");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_quote_snapshots_client_id");

                    b.ToTable("quote_snapshots", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PlanD.Api.Data.BrokerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_broker_claims_brokers_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PlanD.Api.Data.BrokerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_broker_logins_brokers_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PlanD.Api.Data.BrokerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_broker_tokens_brokers_user_id");
                });

            modelBuilder.Entity("PlanD.Api.Data.BrokerCarrier", b =>
                {
                    b.HasOne("PlanD.Api.Data.BrokerUser", null)
                        .WithMany("Carriers")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_broker_carriers_brokers_broker_id");
                });

            modelBuilder.Entity("PlanD.Api.Data.BrokerInvite", b =>
                {
                    b.HasOne("PlanD.Api.Data.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_broker_invites_agencies_agency_id");

                    b.HasOne("PlanD.Api.Data.BrokerUser", null)
                        .WithMany()
                        .HasForeignKey("InvitedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_broker_invites_brokers_invited_by_id");
                });

            modelBuilder.Entity("PlanD.Api.Data.BrokerUser", b =>
                {
                    b.HasOne("PlanD.Api.Data.Agency", "Agency")
                        .WithMany("Brokers")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brokers_agencies_agency_id");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("PlanD.Api.Data.Client", b =>
                {
                    b.HasOne("PlanD.Api.Data.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clients_agencies_agency_id");

                    b.HasOne("PlanD.Api.Data.BrokerUser", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clients_users_broker_id");

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("PlanD.Api.Data.ClientDrug", b =>
                {
                    b.HasOne("PlanD.Api.Data.Client", null)
                        .WithMany("Drugs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_drugs_clients_client_id");
                });

            modelBuilder.Entity("PlanD.Api.Data.ClientNote", b =>
                {
                    b.HasOne("PlanD.Api.Data.Client", null)
                        .WithMany("Notes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_notes_clients_client_id");
                });

            modelBuilder.Entity("PlanD.Api.Data.ClientPharmacy", b =>
                {
                    b.HasOne("PlanD.Api.Data.Client", null)
                        .WithMany("Pharmacies")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_pharmacies_clients_client_id");
                });

            modelBuilder.Entity("PlanD.Api.Data.Consent", b =>
                {
                    b.HasOne("PlanD.Api.Data.Client", null)
                        .WithMany("Consents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consents_clients_client_id");
                });

            modelBuilder.Entity("PlanD.Api.Data.PatientLink", b =>
                {
                    b.HasOne("PlanD.Api.Data.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_links_clients_client_id");
                });

            modelBuilder.Entity("PlanD.Api.Data.QuoteSnapshot", b =>
                {
                    b.HasOne("PlanD.Api.Data.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_snapshots_clients_client_id");
                });

            modelBuilder.Entity("PlanD.Api.Data.Agency", b =>
                {
                    b.Navigation("Brokers");
                });

            modelBuilder.Entity("PlanD.Api.Data.BrokerUser", b =>
                {
                    b.Navigation("Carriers");
                });

            modelBuilder.Entity("PlanD.Api.Data.Client", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("Drugs");

                    b.Navigation("Notes");

                    b.Navigation("Pharmacies");
                });
#pragma warning restore 612, 618
        }
    }
}
